### ISSUE TITLE
Weather Details are not accurate

### ISSUE THREAD

**Issue by myopenflixr** [alexander0042/pirate-weather-ha#30]
Hello,

I wanted to report a couple discrepancies on what is being reported in Pirateweather versus AccuWeather.

Pirateweather is showing current wind speed at 78.62 mph (SSW). It is a bit windy today, but actual wind speed according to AccuWeather is only 7 mph (SSW) with Max Wind Gusts of 20 mph.

Pirateweather is also showing humidity at 76% and AccuWeather is only showing humidity at 68%

Temperature and Air Pressure look to be pretty accurate compared to AccuWeather

Just thought I'd share this with you.

Thanks,
Mike

**Comment by myopenflixr** [comment]
Hi,

For comparisons, I took the following screenshots of Pirateweather and Dark sky to show a side-by-side comparison of the differences in the weather details. These screenshots are about 2 minutes apart in time.

For the most part, they are reporting fairly similar details with the exception of the Wind Speed

![weather_comparison](https://user-images.githubusercontent.com/33140130/146415640-da4420bf-880b-4d09-afcb-fba0036c4851.jpg)

**Comment by alexander0042** [comment]
Hi, thanks for posting this report! It really helps me get a sense of how things are working by comparing against some other sources.

I'm happy seeing the icons and temperatures line up, since precipitation has always been one of the trickier things. Wind speed remains an issue though (also identified here: #16). Do you mind sharing roughly where in the world you are, since that helps with troubleshooting this!

I almost have things set up to use the higher resolution version of the GFS model, so I'm hopeful that helps somewhat here. I'll write up a better process document when the update goes live, but the main issue is that the GFS files were too big to fit in the lambda temporary storage space, so I've moved over to AWS Fargate, which has more room!

**Comment by myopenflixr** [comment]
Hi, I live in Hilliard, OH USA. Zip code 43026

I absolutely love this weather option versus any others that are out there and willing to give you the time it takes to get things working as expected!

I'm also more than happy to help with any testing that you may need from me, however I have virtually no coding skills. and can't help with that aspect

**Comment by alexander0042** [comment]
So this is interesting! It seems to be the classic computing problem of multiple things being incorrect, which makes it really hard to isolate exactly what's wrong. 

Since you're in the US, the first problem doesn't apply to you, but it's pretty interesting! I was surprised to see this, but it turns out there's a bug in the original Dark Sky integration code I pulled from Home Assistant. The integration requests the "ca" units if it detects the install is outside the US. This is fine, but Dark Sky returns wind speed in kph in this case. However, the card displays it using m/s, which is incorrect. 

This one has an easy fix, which I'll push out shortly as a new version- change the requested units to SI! It also appears to be an issue in the current Dark Sky integration for HA, so I'll submit a PR to fix that as well.

However, you're in the US, so this metric issue doesn't explain your problem. I checked the [raw model data ](https://home.chpc.utah.edu/~u0553130/Brian_Blaylock/cgi-bin/hrrr_download.cgi?model=hrrr&field=sfc&date=2021-12-16&link2=grib2) for that date, and the wind speed should have been about 17 mph, not the insane result I'm showing here. The question is why? 

As a first step in debugging, do you mind checking <https://weather.pirateweather.net/> next time you see a weird wind speed? I'm trying to work out if it's an issue with the integration, or my model processing.

Thanks,
Alexander

**Comment by alexander0042** [comment]
Metric wind speeds corrected in commit <https://github.com/alexander0042/pirate-weather-ha/commit/e95083f235817ba3f5653114afe5602ab323b8ae>

**Comment by myopenflixr** [comment]
I have updated to the new version and will continue to monitor. If I do see anything that appears to be off, I'll compare it to 
  [https://weather.pirateweather.net/](https://weather.pirateweather.net/) as you requested and report back.

**Comment by alexander0042** [comment]
Holy cow, I found the issue! Wind speed is a combination of the X and Y components, and I take the vector magnitude sqrt(x^2 + Y^2) to get the wind speed. I did this correctly a dozen times in the script... except once, for the current data, where I had sqrt(x^2 * Y^2). Because wind speed tended to bound around 1-2 m/s, this was a smaller issue than you'd think, but definitely not correct, and more incorrect the higher the winds got! 

I have a major update this weekend, so I've batched this fix as part of that, but starting next week the wind speed issues should be resolved

**Comment by myopenflixr** [comment]
Hi,

I just came across another discrepancy this morning. PirateWeather showing the temp is 36...However, in reality it's closer to 13.

Here's a screenshot of weather pulled from weather.pirateweather.net compared to weather.com. Hilliard, OH around 8:40am EST.
![weather](https://user-images.githubusercontent.com/33140130/148392082-8bc4e0b5-c7d0-47ce-b7d3-fb89059aa65e.jpg)

**Comment by alexander0042** [comment]
Thanks for catching this- I saw this in real time, which really helped troubleshooting!
It's a combination of two things- NOAA's distribution system crashed hard last night (<https://www.nco.ncep.noaa.gov/status/messages/>), which mean Pirate Weather hasn't been able to ingest any new results since then. However, the API *should* gracefully fall back on older forecasts, and it didn't do that.

**Comment by cloneofghosts** [comment]
I'm seeing the same issue on my end with the incorrect data being shown. I looked at the API call and it's showing incorrect data there as well. There is no new API call for the 1.0 release right? I didn't see anything in the docs about if the API call has changed since the 1.0 release.

**Comment by alexander0042** [comment]
Hi,

I should be turning on the V1 version later today (you'll see a new field in the flags for version), so it's NOAA's improvements that should have the largest changes so far. However, I have updated the front end website (<https://weather.pirateweather.net/>) to use the new version while I'm testing it, so let me know if that is looking any better for you?

**Comment by alexander0042** [comment]
Actually, even better idea, if you'd like to help test the new version, change your API url from api.pirateweather.net to dev.pirateweather.net! I use that as my testing endpoint (it calls the latest Lambda code, as opposed to a stable version), but in this case is several steps ahead.

**Comment by cloneofghosts** [comment]
I tried to call dev.pirateweather.net but I get an empty response error when visiting. https://weather.pirateweather.net/ does seem to be better and has fixed the wind speed issue.

**Comment by alexander0042** [comment]
Weird- you might need to go into the developer portal and click subscribe to the .dev backend?

**Comment by cloneofghosts** [comment]
It seems to have fixed itself as the dev url works now.

**Comment by cloneofghosts** [comment]
Just something I noticed yesterday and this morning when looking at the hourly details in the API and on https://weather.pirateweather.net

![image](https://user-images.githubusercontent.com/10248058/148691606-29407240-3d60-4148-a96e-bbe862e0b788.png)

I see that in the hourly section the 4 hours show as rain but the temperature is below the freezing mark. Is it supposed to represent freezing rain or is it just an error with your processing?

**Comment by alexander0042** [comment]
Good spotting! Now that old forecasts are archived for a bit, this way was easier to diagnose, so that's a win!

What you're noticing here is the mismatch between the high resolution, rapidly updating HRRR model that's used for temperate and minute-by-minute data, and the slow, low resolution model (GEFS) that's used for the hourly forecasts. HRRR was showing temperatures below freezing, but since the GEFS model was showing rain, we ended up with this.

![image](https://user-images.githubusercontent.com/26213938/148819319-8c371427-1221-4092-873f-4260fe906bac.png)

These will keep cropping up for the next couple weeks, but the next update to bring in the National Blend of Models should improve this, since temperature and precipitation will come from the same source. The icon is another matter- right now I have it set not to display precipitation unless it's greater than 1 mm/h, but I'm starting to think this is too high- might be better to drop it to 0.5 mm/h as a threshold

**Comment by cloneofghosts** [comment]
Ideally for current conditions it should show the icon if it's greater then 0 but then you might have the problem of it saying rain/snow/sleet if it isn't. I know Dark Sky uses Possible Precipitation for this but that isn't implemented here yet so maybe 0.2/0.3?

For forecasts maybe if it's above a certain percentage (maybe 30%) and above 0 then show the icon? I'm not sure what other sites do but I feel like 30% is reasonable.

**Comment by alexander0042** [comment]
This comment is exactly the reason I put this project together- it shouldn't be a mystery about how a weather API chooses an icon, so thanks for asking this! 

The issue with "any precipitation" is that for really light rain/ snow conditions (think "trace"), you don't want the icon showing as rain/ snow. This is particularly an issue in the winter, where you can get very light snowfall amounts on sunny days. However, 1 mm/h is probably too high of a bar, so I'm thinking 0.25 mm/h as the threshold for the precipitation icon? Percent of precipitation is a good idea, but it would have to come from the global ensemble model, which is less accurate, so want to avoid using that if possible.

**Comment by cloneofghosts** [comment]
I think 0.25mm/h is a good bar to show the icon. What you described is likely why DarkSky uses Possible Drizzle/Flurries/Light Rain as the text for very light precipitation. If the precipitation percentage is coming from a less accurate model then you can not include it for now. Would NBM be better for that or would it still not be super accurate?

Since you merged my issue with this one I will mention that I'm still seeing the issue with the fog icon as stated in the other issue. I know we were discussing the wind icon there as well but never came to any conclusion so maybe wind speeds above 35 km/h would show the icon? Obviously converted for the other units to keep it consistent.

**Comment by cloneofghosts** [comment]
Quick Question about snow and precip rate. I'm seeing this in the API: "precipIntensity": 3.6 and comparing it to Dark Sky I see "precipIntensity": 0.0662

I'm guessing it's not using the snowfall precipitation ratio of 1:10 so it just looks higher then it actually is

**Comment by alexander0042** [comment]
I really love these questions, so keep em coming! 

Great spot here- you're 100% correct that this is an error. I double checked Dark Sky's documentation, and they define that intensity should always be in mm of liquid water per hour (aka, without that 1:10 snow factor), but accumulation should have snow factored in. I think this is kind of weird, since why would someone want intensity in a different unit than accumulation, but if I wanted to make these sorts of decisions, I wouldn't have set up an API with Dark Sky compatibility! 

I've updated the API script so that intensity always returns the liquid water equivalent, and the update should show up in about 20 minutes or so!

**Comment by cloneofghosts** [comment]
Interesting. Maybe having an additional field for the snowfall rate would allow for both to display? Though it would likely end up being precipRate * 10 so it might not be super useful and I'm not sure if the models have a snow / liquid precip rate or if it's just liquid rate. I know another API that has both precip (total liquid precip) and a snow field (just snowfall rate).

**Comment by cloneofghosts** [comment]
That fixed the issue. One thing I'm noticing at the moment is that the reported conditions are off compared to other sites such as Environment Canada/Accuweather/Weather.com.

Right now PirateWeather is showing 0% Cloud Cover and Clear. Those other sites are showing Mostly Cloudy/Cloudy. I'm guessing NBM will help fix the issue but is there no datasets from NOAA on AWS that have current conditions? 

I've also seen the opposite where PirateWeather shows 100% cloud cover on a sunny day.

**Comment by RaptahJezus** [comment]
I am also seeing mismatching weather results. Just for fun, I tried checking weather for Houston, Texas on both DarkSky and PirateWeather. Houston has a pretty big storm passing over it, and this is displayed correctly on DarkSky, but the results from PirateWeather don't seem to agree. PirateWeather's hourly forecast indicates rain through the night, but current forecast has it at cloudy. There is also no precipitation shown. I'm attaching images of both just for reference
![Houston-Pirate](https://user-images.githubusercontent.com/48535973/151865870-c4d168dc-fe54-41ad-9bcf-64c04decb736.jpg)


![Houston-DarkSky](https://user-images.githubusercontent.com/48535973/151865893-06ab3a7d-8b3b-425f-8055-4d372138e0fd.JPG)


Thanks for all your great work on this project so far, it's very exciting to see
.

**Comment by alexander0042** [comment]
Thanks for the updates @cloneofghosts and @RaptahJezus! Those are both really good catches, and I've got separate answers here:
1. Cloud cover is a tricky one to get, since clouds can be super localized, the match can be off. I've looked into using current condition datasets, since there is one that has all the airport/ met station data in it, but only gets updated daily at this point (<https://registry.opendata.aws/noaa-isd/>), so isn't nearly quick enough yet. NBM will fix this to some extent however, so I'm going to start there and see how it works! 
2. I love it when people run these comparisons, so keep it up! Thanks to the V1.0 update, I could actually go back and check exactly what was happening here, and this one was a bug! There was a glitch where it wasn't using the higher resolution forecast for the front end, so that's why you saw that result, combined with the previous comment about what classifies as trace being set to high. I just released V1.1 out into into the wild (it's the default, so you don't have do do anything to use it), and it's been corrected there.

**Comment by cloneofghosts** [comment]
> Thanks for the updates @cloneofghosts and @RaptahJezus! Those are both really good catches, and I've got separate answers here:
> 
> 1. Cloud cover is a tricky one to get, since clouds can be super localized, the match can be off. I've looked into using current condition datasets, since there is one that has all the airport/ met station data in it, but only gets updated daily at this point (https://registry.opendata.aws/noaa-isd/), so isn't nearly quick enough yet. NBM will fix this to some extent however, so I'm going to start there and see how it works!

No worries, I've used other APIs which has the same issues as yours does so it isn't something unique to your API. DarkSky has a ton of different sources so I wonder if it's combining different ones together to get their current conditions?

**Comment by alexander0042** [comment]
Yea, I've checked out that list, and it's pretty extensive! What Dark Sky managed to do a few years ago when they launched was harder than it is now, which is something I'm taking advantage of here. One of the guiding principals of this project is to avoid trying to replicate anything NOAA does, since there's no way I'm ever going to outdo them! Along these lines, since NOAA now has high resolution forecasts down to 15 minute intervals, it let me avoid having to replicate the custom "darksky" item on that list, and generally get the same breadth of data from fewer sources. 

For the forecasts, I use HRRR in the US and Canada to 48 hours, and then GFS for everything else. UV data also comes entirely from GFS, and the ensemble version of the GFS model (GEFS) is what's driving the precipitation estimates. The perk of NBM is that it has its own blend of several models (including the Canadian one), which avoids the really tricky issue of how to blend multiple data sources on my end. 

In the medium term, I'm planing on adding a new url variable that will let people request data from a specific model (ex. models=hrrr,gfs,nbm,cmc). The idea is that the default would continue to return either the highest resolution model or some sort of blend, but let people either select what data they want, or use multiple calls to compare sources. The V1.0 update to move the processing over the fargate was the first step for this, since it'll let me pull in grib files that aren't only available on AWS.

**Comment by cloneofghosts** [comment]
So with HRRR and NBM it will be close to what DarkSky offers then. Will definitely check once NBM is added to see if it helps.

**Comment by alexander0042** [comment]
Exactly! For the minute by minute data, NBM won't change anything, since it's an hourly dateset, but the giant improvement will be to the precipitation probability. Currently, I have to use GFS data for the probability, since HRRR only gives one value, not a range. Since NBM of models is a blend, there's a range of results, which is exactly what's needed for the probabilistic variables. Plus, since the amount, type, and probability of precipitation will all be aligned, there won't be the edge cases where there's a 0% chance of rain but a rain icon, or visa-versa

**Comment by cloneofghosts** [comment]
I've noticed the last few days on https://weather.pirateweather.net/ that the hourly data is showing 0 mm / 0 cm

The data in the API is fine though

**Comment by cloneofghosts** [comment]
Disregard my last comment it seems to be fixed.

I also noticed the same issue last night as mentioned by RaptahJezus. There was some light snowfall which passed through last night but the currently/minutely data. I know at some point last night Kemptville showed snow but that was really all I saw last night in my area.

**Comment by alexander0042** [comment]
Not a coincidence that it's fixed! I saw your comment and worked out the issues (related to the problem that accumulation is always in cm), so it's all good now! It was handy that it's been snowing or raining pretty much everywhere, so lots of places I could check against. 

Re: wind_gust. Your guess is 100% correct. What's weird here is that I honestly can't remember why I made that decision- it may have been that there wasn't guest data in the subhourly, but honestly I'm not sure. Let me check that and get back to you on that one

**Comment by cloneofghosts** [comment]
Looking at your processing script it shows that you are using 10m above ground for wind speeds and surface for gusts. I found this documentation for the sub-hourly fields https://rapidrefresh.noaa.gov/hrrr/GRIB2Table_hrrrncep_subh.txt and it shows that GUST is 10m above ground and there is no surface GUST available

**Comment by alexander0042** [comment]
Ok, this is corrected in the dev back-end for the gust data! I was already processing it (as shown in the scripts- chalking it up as a win for open source that you were able to notice that), so it was just a case of reading that parameter, which was easy (for once!). 

The current conditions is harder. I took a look at it this weekend, and the variable I use to assess cloud cover (TCDC: <https://rapidrefresh.noaa.gov/hrrr/GRIB2Table_hrrrncep_2d.txt>), is only in the hourly data. However, the subhourly does have a composite radar precipitation, which appears promising, but needs more investigation to see how the value returned from that field would relate to the current conditions. If there's precipitation, then that overrides it, but that doesn't help for cloudy/ vs sunny.

**Comment by cloneofghosts** [comment]
I'm sure there's a dataset somewhere which has current conditions but I'm not sure where to find it.

There is a 3D version of HRRR which they call the "analytical/nowcast" model. Might be worth looking into? Though it does seem like the data is 2h behind currently?

**Comment by alexander0042** [comment]
Yea, I've looked into that one, but because it's trailing, I really need a forecast to be able to provide a "current", especially since it takes at least 15 minutes for the data to be loaded into AWS, then converted by the scripts into NetCDF files for the API

**Comment by cloneofghosts** [comment]
I know they have a discussion forum on Github that you could start a thread on https://github.com/NOAA-GSL/GSL-Regional-Model-Forum/discussions otherwise it likely won't be useful. The few google searches for some feeds haven't amounted to anything which is unfortunate. Otherwise I haven't noticed much else in terms of issues with current conditions.

**Comment by alexander0042** [comment]
Yea, it's a tough nut to crack (although that's kind of the point of this project- if it were easy, it wouldn't be any fun).

In North America, NBM should improve things somewhat, since it's integrating data from a wider range of sources, but I don't think it'll be earth shattering. The real answer is to either work radar data in somehow, since it's already gridded and on AWS, or pull real-time observations from airports and whatnot, and then us the closest station (which is what's typically done)

**Comment by cloneofghosts** [comment]
I know that some APIs use a combination of personal weather stations and airports to get their data. While this is good it won't help much if there is no airport nearby or if it doesn't report any conditions. I know there's a few times where there's a difference between what the airport says and what I see at my location.

Working with radar data will help somewhat but it might be tricky to implement? I haven't worked with any of this stuff so I can't say for sure how easy it will be to use them.

**Comment by cloneofghosts** [comment]
I just noticed this when looking at the forecast for Thursday. I know there's supposed to be rain and snow but 200+ mm seems a little ridiculous.

![Screenshot_20220215-132639_DuckDuckGo](https://user-images.githubusercontent.com/10248058/154125560-6bacde6b-fef7-457f-b6b0-767dd7b93aaa.jpg)

**Comment by alexander0042** [comment]
Now that would be a wet day!

I've been thinking about this the last couple days. Since I changed things to always show accumulation in cm and intensity in mm, I knew this would come up at some point, but I'm not sure the best way to "fix" it.

What's happening is that the API always returns accumulations in cm. The weather models return the amount of liquid water per hour, as well as if it is snow or rain, so I use the standard 10:1 ratio to return an amount (in cm). For hourly results, this is easy, since I know what the precipitation type is, and then that's easy to display. But daily data is harder.

Right now, I just add up all the hourly results and spit that out, which works well when it's the same precipitation type all day. But as you can see, when it's a mix of rain and snow, this approach starts to break down. What's happening here is that there's more than 12 hours of rain (so the daily type returns rain), but there's also a fair bit of snow, with that 10x factor. 

Looking at the official Dark Sky docks, accumulation always refers to snow. So maybe the answer here is to keep them separate (which is what newer APIs do), and add another variable for rain accumulation, showing that one separately on the web page. Alternatively, and less of a "breaking change" (although not really, since accumulation for rain should never have been reported for daily data), would be to have it default to the rain accumulation factor (1:1, instead of 10:1) when there's a mix, since this would avoid these crazy results.

Thoughts? 

PS. Don't even get me started on sleet!

**Comment by cloneofghosts** [comment]
> Right now, I just add up all the hourly results and spit that out, which works well when it's the same precipitation type all day. But as you can see, when it's a mix of rain and snow, this approach starts to break down. What's happening here is that there's more than 12 hours of rain (so the daily type returns rain), but there's also a fair bit of snow, with that 10x factor.

When I look now the icon has changed to snow and the correct precipitation amount is being shown. So it's a case of if there is more rain then snow it will use the wrong calculation when displaying on the website.

> Looking at the official Dark Sky docks, accumulation always refers to snow. So maybe the answer here is to keep them separate (which is what newer APIs do), and add another variable for rain accumulation, showing that one separately on the web page. Alternatively, and less of a "breaking change" (although not really, since accumulation for rain should never have been reported for daily data), would be to have it default to the rain accumulation factor (1:1, instead of 10:1) when there's a mix, since this would avoid these crazy results.

It depends on the website for showing the rain accumulation. I know most sites will give a range like 5-10 mm of rain or 10-20 cm of snow as examples. When looking for more details on Accuweather it shows the exact rain amount and the exact snow amount for Thursday afternoon.

![image](https://user-images.githubusercontent.com/10248058/154151766-9e834ecb-0ffd-43c6-b475-507e7649f8a2.png)

Maybe the answer here is to have 3 different precipAccumulation variables:

* precipAccumulation - This would be the total amount of precipitation always in mm. So it would convert the snow using the 1:10 factor
* precipAccumulationRain - Total amount of rain in mm.
* precipAccumulationSnow - Total amount of snow in cm.

It would be more information for those who want it but I'm not sure if it's really necessary or not. More then likely the total accumulation will be equal to rain or snow (after you take into account the 1:10 factor). So maybe just total and snow are needed?

**Comment by cloneofghosts** [comment]
> I've noticed the last few days on https://weather.pirateweather.net/ that the hourly data is showing 0 mm / 0 cm and a rain/snow icon
> 
> The data in the API is fine though

This issue seems to have popped up for Sleet in the daily conditions. Thinking about the accumulation for rain/snow I think it would make the most sense to have a total accumulation in mm and one for snow in cm. Maybe having a separate precip rate for snow in cm/h might be useful?

**Comment by alexander0042** [comment]
Just wanted to pass along a quick update here! There's a few things going on (weather is hard), but at least one of them is fixed! There was an "off-by-one" bug in the processing code, which is what threw the really weird icon != summary issue you saw. That should never happen, and the corrected version is now live. 

In other news, I really love that gridded real-time assimilation source that you posted! They have a 15 minute updating one, which is pretty rapid. I'm going to run some tests this weekend to see how quickly I can ingest it to a netcdf, but it looks promising, especially since it's just 1 time step. This should really improve the current conditions, which I'm learning are a major use case for this sort of thing. 

What time of day were you taking about for the fog icon? I'm thinking the issue might be with the day/ night logic now, so this would help troubleshooting

**Comment by cloneofghosts** [comment]
> What time of day were you taking about for the fog icon? I'm thinking the issue might be with the day/ night logic now, so this would help troubleshooting

It was at night when I saw the issue.

**Comment by cloneofghosts** [comment]
Did the precipIntensity get changed back in the currently data as I see it displaying the snowfall rates in cm/h instead of mm/h. Everywhere else the data is showing the snowfall intensity in mm/h so I'm not sure why currently is displaying the wrong information now.

currently: `"precipIntensity": 3.6,`
minutely: `"precipIntensity": 0.542,`

**Comment by cloneofghosts** [comment]
Any updates on this one? Haven't heard a reply in over two weeks.

**Comment by alexander0042** [comment]
Apologies for the radio silence here! I got sucked into another issue trying to optimize the response time, since it's been slowing down with additional winter weather alerts being issues. 

I never actually adjusted the currently repose, which was an oversight on my part. Thanks for pointing that out, and I've fixed it in for the dev back end, which should go live later this week. In the next couple weeks, I'm going to add a new accumulation variable for rain. Since Dark Sky says that "precipAccumulation" should only be snow, it makes sense to keep this consistent, and clearly solves the 10:1 issue. 

This is the plan: 
- If snow is forecast, "precipAccumulation" will be the snow accumulation, in cm.  
- If rain/ sleet is forecast, "precipAccumulation" will be zero, and the new "liquidAccumulation" will be the rainfall accumulation.
- "precipIntensity" will stay as the Dark Sky compatible mm of liquid water equivalent per hour. I was thinking of adding a "snowIntensity" in cm/h, but I don't think it makes sense in this context. 

I'd love to hear your thoughts on this approach? I think it's the clearest, most compatible way of addressing this permanently, but always open to other ways

**Comment by cloneofghosts** [comment]
Any updates here? I can see that the dataset I posted hasn't been integrated since I'm still seeing the cloud cover issue I pointed out before for the last few hours.

**Comment by alexander0042** [comment]
Thanks again for following up, I really do appreciate it! Also, apologies for "liking" the comment and then not replying, got called to something in the middle of typing this. 

I think this might be easier if we break it into separate issues as they crop up, since it's getting a little busy in this thread. One thing that's definitely solved is the fog icon- as I was driving this morning it was very foggy, and the icon wasn't showing up, so I could troubleshoot it in real time! A really simply mistake, I was using the wrong unit for visibility, so the fog threshold was set to 1 m instead of 1 km, which might be theoretically possible, but would have to be a REALLY foggy day. I've corrected it in a V1.1.5 version that will go live later today. 1 km seems to be the typical definition, so I'll stick with that unless someone suggests something better (<https://web.archive.org/web/20110521015053/http://www.ofcm.gov/fmh-1/pdf/H-CH8.pdf>).

The snow/rain precipitation fix is coded, but I'm waiting to a V1.2 version to push that one live. Since it'll change the way precipitation is returned (albeit improving it), and adding a field that isn't in Dark Sky (albeit improving compatibility with their API), I want to include it in an e-mail, and I try not to send them too frequently to annoy people. It'll definitely happen though! 

And yes, still working on adding that other source. It's lower on the docket, since it likely won't improve things that much compared to HRRR, but is worth doing. I want to improve the alerts to add the rest of the world (the [WMO has a master list](https://severeweather.wmo.int/v2/), so it's possible), a GUI flow for the Home Assistant Integration, and text summaries first though. I'm updating the web page now with a better roadmap, which should help clarify things a little here.

**Comment by cloneofghosts** [comment]
Ah seems like a pretty simple mistake for the fog icon but glad it's fixed.

Alright will break things into different topics when things come up. Unless @myopenflixr has any more issues with the weather details feel free to mark this issue as resolved.

**Comment by alexander0042** [comment]
Oh cool! I hadn't noticed that, but that's definitely it! In particular, they also have the "-ru" gribs, which is what I was looking at adding <https://www.nco.ncep.noaa.gov/pmb/products/rtma/>. Looking at the timestamps, it looks like there's about a 15-minute lag to this data (way better than the ~2 hour lag for HRRR), and the files are small, so I should be able to ingest it quickly.

However, these 15 minute grids have [most variables](https://www.nco.ncep.noaa.gov/pmb/products/rtma/rtma2p5_ru.t1645z.2dvaranl_ndfd.grb2.shtml), but are missing cloud cover and precipitation, which are the two most . It might be better to stick with the hourly data, since it's still pretty quick, and includes everything. Or take both in,

The other potential issue is a "results clash" between HRRR and this dateset. If the HRRR 15 minute data doesn't have precipitation, but this one does, then they'll be weird results showing that it is currently raining but no rain on the minute by minute data. I don't think that's the end of the world, since people understand that one is "now" and one is a forecast, but it's something to think about. 

Sorry for the rambling here- thinking through this as I go along. My next task for this project is re-writing the integration to allow setup in the web GUI, which is almost done, and then this is next on the docket!

**Comment by cloneofghosts** [comment]
I think the information on that page is outdated as according to the 2.8 update in 2020 there's a sky cover analysis in RTMA-RU. Here is the page where I found the information on the 2.8 update https://www.emc.ncep.noaa.gov/emc/pages/numerical_forecast_systems/rtma.php

I haven't seen anywhere that says that RTMA has any precipitation fields which is unfortunate. I still think it's worth using and using the missing fields from RTMA from HRRR. I've seen plenty of times where an API gets their precipitation forecasting wrong that it doesn't really bother me that much personally.

**Comment by cloneofghosts** [comment]
I'm not entirely sure what's going on with HRRR currently but it's definitely way off currently. Not only is the cloud cover/temp off but it's also not showing any rain currently or in the hourly forecast.

I checked against the API and I'm seeing the same issues there as well and I've included a comparison between PirateWeather and Environment Canada as well.

![image](https://user-images.githubusercontent.com/10248058/174858418-3f2843a7-0784-455b-bbc1-66b45edbab4e.png)

**Comment by alexander0042** [comment]
Good catch here! I noticed this one too, particularly today as it was pouring outside. The real win for HRRR was last week, when it successfully predicted the weakening of the storm that hit Ottawa (see [this tweet](https://twitter.com/yow_weather/status/1537593400303575042?s=21&t=6n42YtqAjcRJdYx_WhY24w)). 

These summer storms are incredibly difficult for models to get right, since they’re so localized. I should check the assimilated current weather conditions dataset though, to see if it did a better job capturing these events (it really should, since it’s based on observations!). The way Dark Sky did this was using the radar forecast data, which would be great, but would also add yet another dataset to keep track of…

**Comment by cloneofghosts** [comment]
The current conditions dataset while it doesn't have precipitation (the 3D one does though) it's still at least decent for temperatures and cloud cover. Foe the most part HRRR is at least pretty good at getting precipitation but it went awry today.

Precipitation radar would definitely help but it might only be worth it if there's one that is a global radar since CONUS has HRRR which is better then nothing.

**Comment by myopenflixr** [comment]
I am also noticing pretty significant temperature differences between PirateWeather and weather.com as shown below. Specifically, highs and lows over the next week or so.

![PirateWeather](https://user-images.githubusercontent.com/33140130/175075569-58a97a94-b67b-4ece-ae46-89b689ce0c77.jpg)
![weather_com](https://user-images.githubusercontent.com/33140130/175075575-450af50f-0847-49db-a4f0-a77023b8c440.jpg)

**Comment by alexander0042** [comment]
The high/ low is an interesting way to track these things, and I like how it simplifies things down while still getting the range. These sorts of questions are pushing up against the limits of my understanding of the atmospheric modelling processes, but it seems like the HRRR model in general is struggling with the current pattern (see: <https://twitter.com/webberweather/status/1536347235713224717?s=20&t=SE-7pF1MRz0HJeZ0elqtBw>). 

One interesting point here is that things are pretty aligned for the first 48 hours, then start to really diverge off. What's happening is that the higher resolution HRRR model is used for the initial period, then the lower resolution (and typically less accurate) GFS model takes over fro days 3-14. I'm also wondering if weather.com is showing the air temperature, or the "feels like" temperature, which could cause some differences.

**Comment by cloneofghosts** [comment]
I've found that GFS can be pretty hit or miss at times as yesterday it seemed off and today seems better. I remember you saying that it was the plan to replace it with NBM and I see that's still in the roadmap so it should get better after that switch?

I know that long range forecasting is always difficult and it seemingly changes every our so I don't really pay that much attention to it. Plus we don't know how often weather.com updates their forecasts or what exactly they use to create their forecasts and the fact that GFS only updates every 6h.

**Comment by VAFS001** [comment]
Hi Alexander,
Did the wind speed get corrected in the last update? Mine is still quite a bit off on wind speed and sunrise/sunset data and I am not sure if I was supposed to update or if it does it automagically. (New to HA)

Card data:
![image](https://user-images.githubusercontent.com/17306997/179357298-fbd2c0e0-9b1a-48aa-be9c-f10112eaff73.png)

Pirate Weather data:
![image](https://user-images.githubusercontent.com/17306997/179357332-80fbae52-a064-4a1e-9598-f86dfdb359db.png)

Both API calls are using the same Lat and Lon information.

**Comment by alexander0042** [comment]
Hi,

Thanks for commenting on this issue! Improving the accuracy of the weather details is one of the hardest parts of this, so I really appreciate people taking the time to open issues about it.

Two follow up questions to help figure this out: 
1. Roughly where are you located. There was an issue with the source model [(HRRR)](https://twitter.com/ryanhickman/status/1549461537131319296) that was messing up wind speeds around the Great Lakes, which should be corrected starting tomorrow. 
2. The sunrise and sunset differences suggest that the location isn't being read correctly. To clarify, is the weather card you posted there using Pirate Weather, or another source? Also, roughly when should the sunrise/ sunset be, and is the website correct or off?

**Comment by VAFS001** [comment]
Hi Alexander,

I am using pirate weather for the card.

It is close now, but still a bit off. I am not sure what pirateweather is using for the Palm Bay FL location. I enter my exact lat and lon and the forecast and weather is different.

Here is the data coming through from the pirateweather sensor:
![image](https://user-images.githubusercontent.com/17306997/179848693-8d1bbf3e-4d41-477c-b48b-aaa75c01cfe8.png)

Here is the platform sensor data:
![image](https://user-images.githubusercontent.com/17306997/179849004-f036fe8b-cc01-489e-a1b1-98ed40af2221.png)

Here is the pirateweather data from the pirate weather site:
![image](https://user-images.githubusercontent.com/17306997/179849357-94adf689-da3c-43ac-8715-1a42cd781dcb.png)
![image](https://user-images.githubusercontent.com/17306997/179849441-cf461ebf-ff20-41ab-ab4d-9e55bf2db622.png)

And here is the weather from my sensor:
![image](https://user-images.githubusercontent.com/17306997/179849261-07e20b1e-cecb-42cf-85b1-2f053ee3b2dc.png)

It is the same town and it is not that big to see that large of a swing from the weather data and forecast modeling.

This could just be pirate weather as a source issue.

Thank you for taking a look.

**Comment by cloneofghosts** [comment]
Seems that HRRR is once again off for my location again this morning when it's usually fairly close to other APIs. Comparing against Environment Canada you can see that the temperature is 4 degrees off and the humidity is much lower on Pirate then EC.

![image](https://user-images.githubusercontent.com/10248058/182891176-cd88e1b6-1ddd-4833-95b2-288f8f9ccfff.png)
![image](https://user-images.githubusercontent.com/10248058/182891207-69d24dc1-4150-4d47-8e05-cd291f696054.png)

I know there isn't much you can do to solve the issue but it definitely seems to struggle when the temperature stays cooler/warmer then expected.

**Comment by alexander0042** [comment]
@cloneofghosts, I didn't realize you were nearby to Ottawa! I live on the east side (in Blackburn Hamlet), so it's always nice to see someone else local around here.

These summer storms have been really tricky to get right. Sometimes HRRR nails them, but other times (like today) they emerge out of nowhere and totally miss them. I've contemplated adding in NEXRAD data in (<https://registry.opendata.aws/noaa-nexrad/>), which is how Dark Sky used to do it. However, you hit the nail on the head with your global source comment, since it would make things even more piecemeal from one place to the next, which isn't ideal. Plus, I hate adding something that wouldn't even cover Ottawa! 

My broader plan here is to interoperate the [RTMA dataset](https://registry.opendata.aws/noaa-rtma/) in to help improve this. It's already in a similar grid and data format, so much easier to work with, and since it refreshes every 15 minutes, response times are much faster than HRRR. It's third on the priority list at the moment, behind getting the [Home Assistant Integration](https://github.com/alexander0042/pirate-weather-ha/tree/dev-config-flow) updated and improving the Weather Alerts (since the current implementation slows down the response times a fair bit).

**Comment by cloneofghosts** [comment]
I'm in the south end in Barrhaven which got heavy rain from the storm that just passed through.

HRRR is predicting rain throughout the day and for tomorrow so it's at least correct there.

I know of other APIs that use precipitation radar so unless they combine different radar sources there should be a global one somewhere.

**Comment by alexander0042** [comment]
You're impressively on the ball here! It actually wasn't HRRR or PW, but rather AWS. The processing happens on their Elastic Container Service (running a docker container), which was down for about 13 hours last night: 
![image](https://user-images.githubusercontent.com/26213938/186742839-147fb0e7-c21d-4537-93be-8c3c98bc9bb3.png)

The API's logic in these cases is to keep looking at the latest forecast, stepping forward in time so that the 1 hour forecast becomes the "current" conditions, then 2 hour, and so on. This has worked pretty well so far, and handled the forecast data points well.

Where this logic broke down is for the current conditions after about 4 hours, since I only process the sub-hourly (15-minute) data is 4 hour pieces. This ingests the results faster, saves on processing costs, and since there's typically new results every hour (or at most 2 hours if a run fails) worked perfectly well. However, after that window ends, the script just matches to the nearest time step, which gives the freeze that you saw. Your observation about cloud cover was also dead on, since it isn't in the sub-hourly data, that parameter (along with humidity) comes from the hourly results, which I process out to 18 hours.

The good news here is that it's a super easy fix! There's already error handling logic to fall back to using the GFS results for areas outside of the continental US, so I've added in another check to see if the forecast time frame has been exceeded, in which case it'll switch to the GFS results. Lower resolution, but better than nothing

**Comment by cloneofghosts** [comment]
Is there a particular reason as to why you are falling back to GFS instead of HRRR in the conus area as it would make the most sense but I could see that it might cause issues outside of the CONUS area.

I'm wondering if there's logic for when there's a prolonged outage and the API cannot ingest any new forecast information from the data sources. Does it show all the parameters as 0 or null and what happens to the icon/summary. I didn't see any documentation on this and it would be good to know what to expect if that situation ever happens.

**Comment by alexander0042** [comment]
If you want to test it out, the .dev backend has been updated with the improved logic! So the responses during the outage are now different: 
`https://api.pirateweather.net/forecast/QqOWEnMw0W33rb6yXRXeq2c6m3a2Hfjg4l5RRzwW/45.4215,-75.6972,1661385660?units=ca`
gives a temperature of 26.66 C, while:
`https://dev.pirateweather.net/forecast/QqOWEnMw0W33rb6yXRXeq2c6m3a2Hfjg4l5RRzwW/45.4215,-75.6972,1661385660?units=ca`
gives a temperature of 19.69 C, which is much closer to the [airport temperature](https://weather.gc.ca/past_conditions/index_e.html?station=yow) of 21.6 C at 20:00 on August 24th.

**Comment by alexander0042** [comment]
That's true- it could fall back to the hourly HRRR, since that's read in to 18 hours, so would be a longer "window". I'll see if I can work that in; however, since it's a pretty rare occurrence (this is the first time the processing has failed for more than 2 hours), I also like the simplicity of GFS being the main fallback. I process 10 days of data for each cycle there, and only use 7, which gives me a 3 day widow if anything ever went catastrophically wrong. 

There's a whole new AWS service health API that I could parse into a status page, but in the meantime, I typically use [https://aws-status.info/](https://aws-status.info/), which shows everything. Pirate Weather uses:

- Lambda
- Elastic File System (EFS)
- Elastic Container Service (ECS)
- API Gateway
- Step functions 

All us us-east-1 (N. Virginia)

**Comment by cloneofghosts** [comment]
I saw that you accidentally posted your API key in your first update. I'll delete the email so I don't have it in my possession.

HRRR would be nice to have as a fallback but if it's easier then using GFS would work just as well. I figured you have a buffer of data incase things are down for a prolonged period of time but it would be nice to have documentation on what happens in this situation.

That link is handy and should maybe be posted somewhere on the site? I know other sites use a service such as Uptime Robot as an automated status page but it doesn't account for issues where the API cannot ingest data due to an AWS issue,

**Comment by alexander0042** [comment]
Thanks! It's just a testing key with a pretty low limit, but since I have it copied and pasted into a bunch of QA scripts, it would be a pain to have to replace it. I got too excited that the fixed worked and forgot to sanitize the URLs.

Definitely something that I'll add to the docs though, so thanks for the idea! I've added it to the note, so it'll be there in the next update

**Comment by cloneofghosts** [comment]
No worries it happens. Good to know that it will be documented in the future.

This topic has gotten really long and information is kind of all over the place with the various issues and could probably be closed as there are other similar issues to this one already. I know GitHub supports discussions so it might be worth enabling for these types of issues?

**Comment by alexander0042** [comment]
Mostly since this is the longest running issue thread, I wanted to post a comment here seeing if anyone would be able to test the config-flow update for integration. Doesn't change any of the underlying data, but moves a lot of things to a more modern code base, and allows for setup through the user interface. Instructions are here: <https://github.com/alexander0042/pirate-weather-ha/issues/57>

**Comment by cloneofghosts** [comment]
Something I noticed this morning with the API is that the hourly data is forecasting cloudy conditions all day whereas the currently, minutely and daily blocks are all showing snow.

![image](https://user-images.githubusercontent.com/10248058/206921459-f322091b-4491-40f6-8743-b1ffc71f56c7.png)

I took a look at the JSON response and it is forecasting snow but the intensity is below the 0.25mm threshold to show the snow icon. Maybe the hourly and daily block should be changed to show the snow icon for lower precipitation amounts and maybe have a different icon or maybe even different text like Chance of Snow/Possible Snow would work here? Just throwing out some ideas out there to see if anything sticks.

**Comment by alexander0042** [comment]
Yea, the snow icon threshold is an long standing issue. It's one of those tricky things that's full of edge cases and right on the bounds of what I trust the underlying model data with anyway.

I really like your suggestion for the summary text though! My priority list now that the new Home Assistant integration is released is:
1. Better alerts processing, hopefully with global coverage and much less computational overhead.
2. Investigate if it's feasible to use radar data for the currently conditions <https://github.com/alexander0042/pirateweather/issues/10>.
3. Text summaries, which this fits right into. Dark Sky already has a [translations library](https://github.com/alexander0042/translations), so it'll be a case of fitting this data into their syntax. However, adding in XXX/windy as an intermediary step is a really easy way to add a bit of granularity to the existing setup

**Comment by cloneofghosts** [comment]
I would assume that the same could happen with rain but might be less likely because of the 1:10 ratio for snow? 

I don't see NBM/RTMA in the list but I would assume they're planned but maybe have no set priority?

The road map on the documentation repo needs updated now that the HA update has been released.

**Comment by cloneofghosts** [comment]
It might make more sense to do this when you implement the text summaries but if you want to add more granularity to the API you could implement the different conditions without doing the full text summaries. I'm not sure what is available from the datasets but maybe something like this list would work?

* Clear
* Mainly Clear
* Partly Cloudy
* Mostly Cloudy
* Cloudy
* Drizzle
* Light Rain
* Rain
* Heavy Rain
* Flurries
* Light Snow
* Snow
* Heavy Snow
* Freezing Rain
* Sleet
* Thunderstorm
* Heavy Thunderstorm
* Hail
* Unknown Precipitation
* Mist
* Haze
* Fog
* Not Available

I'm sure there's a calculation for thunderstorms out there which probably uses CAPE/Lifted Index and I know that Mist/Haze are visibilities between 10 and 1 km with the difference being the humidity. If it's above a certain percentage it's mist otherwise it would be haze.

**Comment by cloneofghosts** [comment]
I wonder if anything from [EUMETSAT](https://www.eumetsat.int/) would be useful. I know they have a ton of different datasets that might help but might be hard to integrate.

**Comment by cloneofghosts** [comment]
Apparently Icon-D2 has 15m data over Central Europe which is updated every 3h which might be useful? I know it isn't on AWS and it looks like they have separate files for each parameter which might be a pain to work with. Still might be worth looking into over Europe

[https://www.dwd.de/EN/ourservices/nwp_forecast_data/nwp_forecast_data.html](https://www.dwd.de/EN/ourservices/nwp_forecast_data/nwp_forecast_data.html)

**Comment by Nertskull** [comment]
Love this plugin. Hopefully this is the correct thread to post in.

I'm getting incorrect future forecasts at times. Today it's telling me the high temp forecast for Tuesday is 58 F.  But accuweather, NWS, google give highs in the 70-72 F range.  That seems to be a fairly large inconsistency. And I've had other days with 8+ degrees difference, including other seen this upcoming week.  But sometimes even same day highs have differences of 10+ degrees.

![image](https://github.com/alexander0042/pirate-weather-ha/assets/11792025/6d71e7c5-fcf7-4063-92af-a195a3e7fe01)

![image](https://github.com/alexander0042/pirate-weather-ha/assets/11792025/c36c7d99-fef8-47c2-b332-1ae0ea62fd03)

![image](https://github.com/alexander0042/pirate-weather-ha/assets/11792025/73f998c9-bd80-42d4-9e97-83ba4349d9fa)

![image](https://github.com/alexander0042/pirate-weather-ha/assets/11792025/cc849d8f-51ce-493a-b1ee-0f59bf8666bb)

This was tested in Columbus OH, usa

**Comment by alexander0042** [comment]
Interesting- looking at Columbus today, it's looking like everything is well aligned with other sources. Can you do a quick double check if the daily high/ low temperatures match with [Merry Sky for Columbus](https://merrysky.net/forecast/columbus%20ohio/us)? Since they're pulling from the same back-end, they should, but would indicate something else is wrong here

**Comment by Nertskull** [comment]
It's matching better today, but it's not perfect.  This is what the High's are for the next 5 days (Mon-Fri).  All sources say listed for Upper Arlington (columbus suburb)

79 - 74 - 66 - 71 - 71 (my HA pirate weather)
77 - 64 - 65 - 67 - 75 (merry sky)
76 - 68 - 69 - 75 - 80 (weather.com/google)
76 - 68 - 68 - 73 - 75 (accuweather)

So Tuesday is still pretty off, others match reasonably well. But not the same as Merry Sky

**Comment by cloneofghosts** [comment]
I just tested on my end and I wasn't sure whether to put it here or in https://github.com/alexander0042/pirateweather/issues/30 but I am seeing the same issue as Nertskull

HA:
![image](https://github.com/alexander0042/pirate-weather-ha/assets/10248058/e1b36f2d-8b18-4663-b267-9c9a2f505f72)

MerrySky (I hid some elements to show a better comparison image):
![image](https://github.com/alexander0042/pirate-weather-ha/assets/10248058/c653fe07-a1e7-4d0e-91c4-d04409427014)

I am aware that MerrySky caches things so maybe that's causing the differences? It could also be that HA uses the daily high/low temperatures for the daily high/low and MerrySky is calculating it for the day based off of the extended hourly conditions?

**Comment by th0mcat** [comment]
Glad I found this issue.  Over the last couple days, I've noticed a large temperature variance in 7 day forecasts for days 3-7.  

Date | Wunderground | weather.gov | Merry Sky |   | Difference Wunderground | Difference weather.gov
-- | -- | -- | -- | -- | -- | --
1-Jun | 88 | 90 | 88 |   | 0 | 2
2-Jun | 86 | 90 | 87 |   | -1 | 3
3-Jun | 90 | 91 | 82 |   | 8 | 9
4-Jun | 90 | 87 | 80 |   | 10 | 7
5-Jun | 86 | 86 | 69 |   | 17 | 17
6-Jun | 79 | 79 | 67 |   | 12 | 12
7-Jun | 79 | 81 | 67 |   | 12 | 14

![image](https://github.com/alexander0042/pirate-weather-ha/assets/37344783/d1cbfd63-c1c1-44e6-aaf7-0d07a0a8a574)

![image](https://github.com/alexander0042/pirate-weather-ha/assets/37344783/46b5c931-a829-4f3d-b44b-9d7f292a610b)

![image](https://github.com/alexander0042/pirate-weather-ha/assets/37344783/660c0595-90e7-417c-837a-0096657c5aaa)


I'd never seen a 17-degree disagreement in high temperature forecast for the same day before, so I figured that must mean something is probably weird.  I can provide ZIP code privately via Matrix/Email/Reddit, if needed.

**Comment by cloneofghosts** [comment]
If you query the API in your browser do you get better results than MerrySky? I've noticed that what MerrySky says and what is shown in the API can differ so it's possible that the API has more accurate results then MerrySky.

I will also note that after 48h out after the current forecast the API switches to the global GFS data which isn't as good as the HRRR data and the planned switch to using NBM data will help solve things. Out of curiosity I compared different APIs for my location to see the difference

|        | Environment Canada | PirateWeather | MerrySky | Open-Meteo | WeatherBit | Accuweather | Weather.com | WorldWeatherOnline | WeatherBug | Foreca |
|--------|--------------------|---------------|----------|------------|------------|-------------|-------------|--------------------|------------|--------|
| June 1 | 33                 | 33            | 33       | 33         | 33         | 33          | 34          | 29                 | 32         | 32     |
| June 2 | 33                 | 32            | 29       | 32         | 32         | 32          | 32          | 29                 | 29         | 29     |
| June 3 | 23                 | 20            | 20       | 20         | 22         | 23          | 22          | 18                 | 23         | 21     |
| June 4 | 25                 | 20            | 20       | 20         | 23         | 23          | 23          | 19                 | 23         | 21     |
| June 5 | 24                 | 16            | 13       | 16         | 21         | 19          | 20          | 17                 | 19         | 18     |
| June 6 | 22                 | 13            | 14       | 10         | 20         | 20          | 18          | 12                 | 20         | 18     |
| June 7 | 24                 | 11            | 14       | 17         | 21         | 19          | 19          | 12                 | 19         | 19     |

**Comment by cloneofghosts** [comment]
Hopefully NBM can be added sometime this year though it has the lowest priority on the roadmap unfortunately.

**Comment by josephny** [comment]
> I'm in the south end in Barrhaven which got heavy rain from the storm that just passed through.
> 
> HRRR is predicting rain throughout the day and for tomorrow so it's at least correct there.
> 
> I know of other APIs that use precipitation radar so unless they combine different radar sources there should be a global one somewhere.
> 
> EDIT: NEXTRAD does in fact cover Ottawa as seen on their radar viewer. Not sure how far it goes into Canada but it is particularly included.
> 
> EDIT2: I don't know if either of these will be useful but it might help in places outside of the US? [NOAA ](https://madis.ncep.noaa.gov/)[Madis](https://madis.ncep.noaa.gov/)
> 
> EDIT3: I'm actually seeing PW saying that it's raining when in actuality it isn't. The minutely is also showing heavy rain forecasted which is also very wrong.
> 
> ![image](https://user-images.githubusercontent.com/10248058/185950337-965f9bc0-f862-4844-9cec-8ec7c4a4da52.png)
> 
> ![image](https://user-images.githubusercontent.com/10248058/185950450-96ad792b-f38a-4985-b70f-47723941ef7f.png)


Sorry to revive this old thread, but I'm hoping you would post the code for this (or these) cards?

Thank you.

**Comment by cloneofghosts** [comment]
This thread was made before the processing repo was created so most people just posted their issues here whether they were a HA issue or an API issue.

Those two screenshots that I posted were the old Pirate Weather website and the Environment Canada website. Neither of those screenshots were screenshots of any HA integrations. I don't know if there are any weather cards out there which can mimic either of those two websites so you'll have to look around.

**Comment by alexander0042** [comment]
@cloneofghosts is correct, these aren't Home Assistant cards, so don't have HA specific code unfortunately. However, the code to run the old Pirate Weather website is available here: <https://github.com/alexander0042/weather-vue>. It's all written in javascript/ html. so might be possible to convert it to a HA card?

**Comment by cloneofghosts** [comment]
@alexander0042 The only thing which might not be possible in HA would be the precipitation for the hour graph since the minutely data isn't available in HA. There was this issue https://github.com/alexander0042/pirate-weather-ha/issues/49 asking about how to create it but it went stale.

With the correct card you could be able to combine different pieces together to create a similar looking experience to the old website.

**Comment by cloneofghosts** [comment]
@alexander0042 I'm wondering if addressing this issue will be a part of the 2.0 release or if it will come later. I don't think you've mentioned what's on tap for the 2.0 release besides open sourcing the project. Could be a good idea to post somewhere (maybe in the roadmap and/or as a github project) so we know what's planned for that release.

**Comment by alexander0042** [comment]
Great point- would also help me stay focused on the most important details as well! While the theoretical approach to the API will always limit the accuracy to whatever the underlying models produce, the 2.0 version should have some improvements. The biggest change will be fixing how daily high and low temperatures are calculated for day 0, as well as providing much more accurate "time-machine" results for previous week or so. Beyond that, the big accuracy improvements will be from adding in National Blend of Models; however, I'm still thinking though how best to incorporate it- either adding a flag where it could be requested instead of HRRR, using it as the default, or some sort of blend of the two. I'm leaning towards just making it the default at this point and having HRRR available as a flag

**Comment by cloneofghosts** [comment]
> Beyond that, the big accuracy improvements will be from adding in National Blend of Models; however, I'm still thinking though how best to incorporate it- either adding a flag where it could be requested instead of HRRR, using it as the default, or some sort of blend of the two. I'm leaning towards just making it the default at this point and having HRRR available as a flag

I could be wrong but my understanding is that NBM starts its forecasts from h1 whereas HRRR starts from h0. So if we're using NBM + HRRR then wouldn't it make sense to use HRRR for current conditions and then use NBM for forecasts?

RTMA could also be useful for current conditions but you may want to wait until 3DRTMA is released in 2025 (it got delayed from 2024) as it will have all the same data as HRRR but with the frequency of the current RTMA-RU.
