### ISSUE TITLE
Malformed forecast URL causes 403 response from API

### ISSUE THREAD

**Issue by esenciadev** [alexander0042/pirate-weather-ha#40]
integration is making requests using comma separated lat & lon, which is causing Pirate Weather API to return a 403 Not Authorized. I confirmed that if the values are URL encoded correctly, the call returns a 200. Example of the requested URL:

https://api.pirateweather.net/forecast/MY_API_KEY/33.333333,-111.111111?units=us

My location is not specified in configuration, it is updated via an automation using a service calls (location changes daily as this is in an RV). 

Environment:
HACS | 1.22.0
Pirate Weather | latest as of 2/6/2022
Version | core-2022.2.1
Installation Type | Home Assistant Container
Development | false
Supervisor | false
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.7
Operating System Family | Linux
Operating System Version | 5.10.63-v7l+
CPU Architecture | armv7l

**Comment by alexander0042** [comment]
Thanks using this integration and posting your environment details! 

To clarify here: is the example URL you posted there working for you, or is that the issue? The location should be comma separated (with the date as an optional third argument), so that syntax looks correct. Or are you URL encoding the lat/lon/API, and that's returning the 403?

**Comment by esenciadev** [comment]
The example URL I included is what the pirate weather integration for HA is making a request for, and getting the 403 response. I am able to consistently reproduce the error using Postman/CURL and the full URL (with my API key). If I use the swagger front-end on pirateweather.com, browse to the forecast endpoint, enter my API key, location as a comma separated string, it generates a URL with the comma escaped (%2C), and gets a 200 response code from the API. Screenshot of this is below.

<img width="1356" alt="Screen Shot 2022-02-06 at 1 14 05 PM" src="https://user-images.githubusercontent.com/130012/152701668-c87a055f-20f2-456f-b8f0-f1729662bc0d.png">

**Comment by alexander0042** [comment]
Ok, that's interesting (and as a side note, happy that the front end is being used). 

The "correct" way to call the API is using a comma, so that's why the HA integration is using it. I'm not totally sure why the front end replaces it with the escaped character, but I think I've fixed that now- you can try it using the dev.pirateweather.net back end.

That doesn't solve the initial question about the 403 error though. Troubleshooting step 1, can you double check that you're subscribed to the API in the console (it's the button next to the logo)?

**Comment by esenciadev** [comment]
I was not subscribed; after hitting that and restarting HA, I still get the same 403 response. I confirmed that the button next to the pirate weather logo changed to "unsubscribe".  Is there a propagation time, or another step that I missed?

**Comment by alexander0042** [comment]
Ahh, that issue! I really wish there was some way to get rid of that extra step, but haven't found one yet. 

It takes about 20 minutes to propagate, so let me know if it started working here

**Comment by esenciadev** [comment]
It's working great now, thank you.
